---
- name: provisioning  
  hosts: build
  become: yes

  tasks:
  - name: Install maven jdk
    apt:
      name:
        - git
        - default-jdk
        - maven
        - rsync
      state: present
      update_cache: true
  - name: clone repo of github
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git 
      dest: /usr/home

  - name: Build maven
    command: chdir=/home/user/boxfuse-sample-java-war-hello mvn package
  #- name: Wait build *war target/hello-1.0.war
    wait_for:
     patch: /home/user/boxfuse-sample-java-war-hello/target/hello-1.0.war
  - name: Synchronization of src on the control machine to dest on the remote hosts
    synchronize:
      src: /home/user/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp

- name: Provisioning tomcat
  hosts: web
  become: yes
  tasks:
  - name: Install Tomcat9
    apt:
      name: 
        - default-jdk
        - tomcat9
        - rsync
      state: present
      update_cache: true
  - name: Transfer artifact to web
    synchronize:
      src: /tmp
      dest: /var/lib/tomcat9/webapps
  - name: Ensure started service tomcat
    service:
     name: tomcat
     state: started